FROM python:3.10-slim-bookworm
	
WORKDIR /srv/app
COPY ./discord-spider/requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

# run app
CMD ["gunicorn", "--bind", "0.0.0.0:8888", "app:app"]  