name: cynthia
services:

  web:
    build: 
      context: ./
      dockerfile:  Dockerfile.web
    ports:
      - 8080:8080
    volumes:
      - ./html:/var/www/html
      - ./settings.conf:/etc/nginx/conf.d/settings.conf

  php:
    build: 
      context: ./
      dockerfile:  Dockerfile.php
    volumes:
      - ./html:/var/www/html
      - ./settings.ini:/usr/local/etc/php/conf.d/settings.ini